### ISSUE TITLE
Strange behavior with spawn

### ISSUE THREAD

**Issue by ray-delossantos** [ysbaddaden/pool#1]
Hello:

I tried the pool manager in a big project and sometimes the pool doesn't execute a postgres function correctly running in fast while loop, spawning 10 or plus fibers. I'm using the new fiber implementation released 2 days ago.  

Is there's any spec that test this kind of behavior?

**Comment by ysbaddaden** [comment]
No I don't have a test for requests in tight loops. Do you have more details or debug about what's happening?

**Comment by ray-delossantos** [comment]
I'm working on isolating the problem. When i call the pg.exec directly (without pool) it works correctly. I'll try to prepare a complete code.

**Comment by ray-delossantos** [comment]
I'm going to close this issue because i realized that the update was called before the insert has been commited. The reconnection allowed enough time for the insert to be commited and that's why the code without pool, worked. Sorry for the invalid bug report.

**Comment by ysbaddaden** [comment]
I'm glad you found the root cause.
