### ISSUE TITLE
Crystal/Mysql

### ISSUE THREAD

**Issue by crisward** [ysbaddaden/pool#6]
``` crystal
require "./mess/*"
require "kemal"
require "json"
require "mysql"
require "pool/connection"

db = ConnectionPool.new(capacity: 25, timeout: 0.01) do
  DB.open(ENV["DATABASE_URL"])
end

class User
  DB.mapping({
    id: Int32,
    first_name:   {type: String, nilable: true},
    surname: {type: String, nilable: true},
  })
  JSON.mapping({
    id: Int32,
    first_name:   {type: String, nilable: true},
    surname:  {type: String, nilable: true},
  })
end

get "/" do |env|
  db.connection do |conn|
    env.response.content_type = "application/json"
    User.from_rs(conn.query("SELECT id,first_name,surname FROM users")).to_json
  end
end

Kemal.run
```

This doesn't seem to work with https://github.com/crystal-lang/crystal-mysql/
The second request gets a DB Pool Exhausted (Exception), not sure if I'm doing something wrong, very new to crystal.

Any help you can offer would be very much appreciated.

**Comment by ysbaddaden** [comment]
I can't test right now, but as far as ConnectionPool is concerned, there is only one exception that may be raised: `IO::Timeout` when it takes more time than allowed to get a comnection from the pool. Maybe the pool exhausted error comes from the MySQL driver?

**Comment by crisward** [comment]
I think you may be right... I tested with another pool (in development on main crystal/db) and it does the same thing. Seems the mysql driver to killing it's connections, just can't work out why. I'll close this as I'm pretty sure your module is not at fault.

Thanks.
